services:
  postgres:
    image: postgres:15
    container_name: guac-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 'hello@69'
      POSTGRES_USER: 'guacamole_user'
      POSTGRES_DB: 'guacamole_db'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - net-lab-internal

  guacd:
    image: guacamole/guacd:latest
    container_name: guacd
    restart: always
    depends_on:
      - postgres
    networks:
      - net-lab-internal
    extra_hosts:
      - "host.docker.internal:host-gateway"

  guacamole:
    image: guacamole/guacamole:latest
    container_name: guacamole
    restart: always
    depends_on:
      - guacd
    ports:
      - "3001:8080"
    environment:
      GUACD_HOSTNAME: 'guacd'
      POSTGRESQL_HOSTNAME: 'postgres'
      POSTGRESQL_DATABASE: 'guacamole_db'
      POSTGRESQL_USERNAME: 'guacamole_user'
      POSTGRESQL_PASSWORD: 'hello@69'
    networks:
      - net-lab-internal

  backend:
    build: ./backend
    container_name: backend
    image: sponge24/network-lab-backend:latest
    restart: always
    depends_on:
      - guacamole
    ports:
      - "8000:8000"
    volumes:
       - ./overlays:/app/overlays
       - ./images:/app/images:ro
    devices:
      - /dev/kvm
    privileged: true
    networks:
      - net-lab-internal

  frontend:
    build: ./frontend
    container_name: frontend
    image: sponge24/network-lab-frontend:latest
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    depends_on:
      - backend
    networks:
      - net-lab-internal
networks:
  net-lab-internal: 
    driver: bridge

volumes:
  postgres-data: